server:
  port: 8080

spring:
  datasource:
    hikari:
      maximum-pool-size: 50

    url:
    username: testuser
    password: testpwd


  rsocket:
    server:
      port: 7000
      transport: websocket
      mapping-path: /rsocket

  batch:
    job:
      enabled: false
